name: cli_app_that_uses_dart_foo
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.3.0-234.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dart_foo:
    path: ../dart_foo/packages/dart_foo

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
